// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/liletestone.proto

package liletestone // import "github.com/karux/liletestone"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRequest) Reset()         { *m = GetRequest{} }
func (m *GetRequest) String() string { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()    {}
func (*GetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_liletestone_1b49beb64e3e21bf, []int{0}
}
func (m *GetRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRequest.Unmarshal(m, b)
}
func (m *GetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRequest.Marshal(b, m, deterministic)
}
func (dst *GetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRequest.Merge(dst, src)
}
func (m *GetRequest) XXX_Size() int {
	return xxx_messageInfo_GetRequest.Size(m)
}
func (m *GetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRequest proto.InternalMessageInfo

func (m *GetRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetResponse) Reset()         { *m = GetResponse{} }
func (m *GetResponse) String() string { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()    {}
func (*GetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_liletestone_1b49beb64e3e21bf, []int{1}
}
func (m *GetResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetResponse.Unmarshal(m, b)
}
func (m *GetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetResponse.Marshal(b, m, deterministic)
}
func (dst *GetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetResponse.Merge(dst, src)
}
func (m *GetResponse) XXX_Size() int {
	return xxx_messageInfo_GetResponse.Size(m)
}
func (m *GetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetResponse proto.InternalMessageInfo

func (m *GetResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*GetRequest)(nil), "liletestone.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "liletestone.GetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// LiletestoneClient is the client API for Liletestone service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type LiletestoneClient interface {
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
}

type liletestoneClient struct {
	cc *grpc.ClientConn
}

func NewLiletestoneClient(cc *grpc.ClientConn) LiletestoneClient {
	return &liletestoneClient{cc}
}

func (c *liletestoneClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, "/liletestone.Liletestone/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LiletestoneServer is the server API for Liletestone service.
type LiletestoneServer interface {
	Get(context.Context, *GetRequest) (*GetResponse, error)
}

func RegisterLiletestoneServer(s *grpc.Server, srv LiletestoneServer) {
	s.RegisterService(&_Liletestone_serviceDesc, srv)
}

func _Liletestone_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LiletestoneServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/liletestone.Liletestone/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LiletestoneServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Liletestone_serviceDesc = grpc.ServiceDesc{
	ServiceName: "liletestone.Liletestone",
	HandlerType: (*LiletestoneServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _Liletestone_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "model/liletestone.proto",
}

func init() {
	proto.RegisterFile("model/liletestone.proto", fileDescriptor_liletestone_1b49beb64e3e21bf)
}

var fileDescriptor_liletestone_1b49beb64e3e21bf = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0xcf, 0xcd, 0x4f, 0x49,
	0xcd, 0xd1, 0xcf, 0xc9, 0xcc, 0x49, 0x2d, 0x49, 0x2d, 0x2e, 0xc9, 0xcf, 0x4b, 0xd5, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x46, 0x12, 0x52, 0x92, 0xe1, 0xe2, 0x72, 0x4f, 0x2d, 0x09, 0x4a,
	0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xe2, 0xe3, 0x62, 0xca, 0x4c, 0x91, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x0c, 0x62, 0xca, 0x4c, 0x51, 0x92, 0xe5, 0xe2, 0x06, 0xcb, 0x16, 0x17, 0xe4, 0xe7, 0x15,
	0xa7, 0xa2, 0x4b, 0x1b, 0x79, 0x72, 0x71, 0xfb, 0x20, 0xcc, 0x12, 0xb2, 0xe2, 0x62, 0x76, 0x4f,
	0x2d, 0x11, 0x12, 0xd7, 0x43, 0xb6, 0x13, 0x61, 0xba, 0x94, 0x04, 0xa6, 0x04, 0xc4, 0x60, 0x25,
	0x06, 0x27, 0xb9, 0x28, 0x99, 0xf4, 0xcc, 0x92, 0x8c, 0xd2, 0x24, 0xbd, 0xe4, 0xfc, 0x5c, 0xfd,
	0xec, 0xc4, 0xa2, 0xd2, 0x0a, 0x64, 0xa7, 0x27, 0xb1, 0x81, 0xdd, 0x6e, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x45, 0x31, 0x8c, 0xe4, 0xd6, 0x00, 0x00, 0x00,
}
